import type { CatalogProduct } from "./types";

export const COFFEE_CATALOG: CatalogProduct[] = [
  {
    id: "train-penang-coffee-o-20",
    merchant: "Shun Dat",
    merchantType: "shopify-sandbox",
    name: "Train Brand Penang Coffee O",
    description: "20 no-added-sugar coffee sachets",
    quantity: 20,
    noAddedSugar: true,
    inStock: true,
    deliveryRegion: "SG",
    itemPriceSgd: 6.5,
    deliveryPriceSgd: 3.5,
    deliveryDays: 1,
    rating: 4.8,
    imageUrl: "https://www.shundat.com/cdn/shop/files/sg-11134207-821g7-mgxqmr4espvue1.jpg?v=1762870349&width=900",
    productUrl: "https://www.shundat.com/",
  },
  {
    id: "gold-kili-black-coffee-20",
    merchant: "Local Pantry",
    merchantType: "shopify-sandbox",
    name: "Gold Kili Instant Black Coffee",
    description: "20 unsweetened black-coffee sachets",
    quantity: 20,
    noAddedSugar: true,
    inStock: true,
    deliveryRegion: "SG",
    itemPriceSgd: 7.1,
    deliveryPriceSgd: 4.2,
    deliveryDays: 2,
    rating: 4.5,
    imageUrl: "https://www.shundat.com/cdn/shop/files/sg-11134207-821g7-mgxqmr4espvue1.jpg?v=1762870349&width=900",
    productUrl: "https://www.shundat.com/",
  },
  {
    id: "oldtown-3in1-20",
    merchant: "Kopitiam Market",
    merchantType: "shopify-sandbox",
    name: "OldTown 3-in-1 Classic",
    description: "20 sweetened white-coffee sachets",
    quantity: 20,
    noAddedSugar: false,
    inStock: true,
    deliveryRegion: "SG",
    itemPriceSgd: 6.2,
    deliveryPriceSgd: 3.1,
    deliveryDays: 1,
    rating: 4.7,
    imageUrl: "https://www.shundat.com/cdn/shop/files/sg-11134207-821g7-mgxqmr4espvue1.jpg?v=1762870349&width=900",
    productUrl: "https://www.shundat.com/",
  },
];
